CREATE DATABASE ConvenienceShop
GO
USE ConvenienceShop
GO
CREATE TABLE TypeOfProduct(
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	TypeName NVARCHAR(50) NULL
)

--Insert
go
insert into TypeOfProduct values('A1'),('A2'), ('A3')
go
--end

GO
CREATE TABLE Producer(
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	ProducerName NVARCHAR(50) NULL,
	Address NVARCHAR(50) NULL,
	Phone NVARCHAR(11) NULL
)
GO
CREATE TABLE Product(
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	TypeID INT NOT NULL,
	ProductName NVARCHAR(50) NULL,
	ProducerID INT NOT NULL,
	Price FLOAT NULL,
	Status NVARCHAR(10) NULL,
	CONSTRAINT FK_TypeID FOREIGN KEY(TypeID) REFERENCES TypeOfProduct(Id),
	CONSTRAINT FK_ProducerID FOREIGN KEY(ProducerID) REFERENCES Producer(Id)
)
GO
CREATE TABLE Staff(
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Name NVARCHAR(50) NULL,
	DateOfBirth DATETIME NULL,
	Gender NVARCHAR(10) NULL,
	Email NVARCHAR(50) NULL,
	Address NVARCHAR(50) NULL,
	Phone NVARCHAR(11) NULL
)
GO
CREATE TABLE Account(
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	AccountName NVARCHAR(30) NULL,
	Password NVARCHAR(30) NULL
)
GO
CREATE TABLE Bill(
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	DateOfSale DATETIME NULL
)
GO
CREATE TABLE BillInfo(
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	BillID INT NOT NULL,
	TypeID INT NOT NULL,
	ProductID INT NOT NULL,
	Discount INT NULL,
	TotalPrice FLOAT NULL
)
GO